# Step 1: Installation and Setup

In [4]:
pip install tensorflow

Note: you may need to restart the kernel to use updated packages.


In [6]:
import tensorflow as tf

In [8]:
print(tf.__version__)

2.6.2


In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# Step 2: Data preprocessing

In [4]:
training_data = pd.read_csv('training_set.csv')

In [6]:
training_data.head()

Date       Open       High        Low      Close  Adj Close    Volume
0  2018-09-12  58.636002  58.930500  57.917999  58.140999  58.140999  25910000
1  2018-09-13  58.536999  58.930500  58.142502  58.766499  58.766499  28624000
2  2018-09-14  58.955002  59.021252  58.416500  58.626499  58.626499  18880000
3  2018-09-17  58.507000  58.862000  57.701500  57.802502  57.802502  26130000
4  2018-09-18  57.854500  58.804001  57.854500  58.061001  58.061001  24072000

In [8]:
training_data.tail()

Date       Open       High        Low      Close  Adj Close  \
246  2019-09-05  59.576500  60.652000  59.576500  60.569000  60.569000   
247  2019-09-06  60.406502  60.600750  60.126099  60.246498  60.246498   
248  2019-09-09  60.200001  61.000000  59.631001  60.220501  60.220501   
249  2019-09-10  59.757500  60.500000  59.729000  60.299999  60.299999   
250  2019-09-11  60.170502  61.130001  60.110001  61.008499  61.008499   

       Volume  
246  28162000  
247  21442000  
248  29438000  
249  25202000  
250  26140000

In [10]:
training_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 251 entries, 0 to 250
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   Date       251 non-null    object 
 1   Open       251 non-null    float64
 2   High       251 non-null    float64
 3   Low        251 non-null    float64
 4   Close      251 non-null    float64
 5   Adj Close  251 non-null    float64
 6   Volume     251 non-null    int64  
dtypes: float64(5), int64(1), object(1)
memory usage: 13.9+ KB


In [12]:
training_set = training_data.iloc[:, 1:2].values

In [15]:
training_set.shape, training_data.shape

((251, 1), (251, 7))

In [17]:
# feature scaling
from sklearn.preprocessing import MinMaxScaler
sc = MinMaxScaler(feature_range=(0,1))
training_set_scaled = sc.fit_transform(training_set)

In [19]:
training_set_scaled

array([[0.66251258],
       [0.65591458],
       [0.68377216],
       [0.65391532],
       [0.61042982],
       [0.63672112],
       [0.68673771],
       [0.72675757],
       [0.61069646],
       [0.67394191],
       [0.70393198],
       [0.70919675],
       [0.72632438],
       [0.75304887],
       [0.72329219],
       [0.77007659],
       [0.73785393],
       [0.64511825],
       [0.58717097],
       [0.57397524],
       [0.52375878],
       [0.33002324],
       [0.44685115],
       [0.44988328],
       [0.43548814],
       [0.50836398],
       [0.49296891],
       [0.39810054],
       [0.43038984],
       [0.35651434],
       [0.43435532],
       [0.32619125],
       [0.21036326],
       [0.36177945],
       [0.11516161],
       [0.28627129],
       [0.33955353],
       [0.33265583],
       [0.27024323],
       [0.21852708],
       [0.31689441],
       [0.39146948],
       [0.3335222 ],
       [0.29153614],
       [0.23122298],
       [0.25358212],
       [0.23595467],
       [0.284

In [21]:
# creating a data structure with 60 timesteps and 1 output
x_train =  []
y_train = []

for i in range(60, 251):
    x_train.append(training_set_scaled[i-60:i, 0])
    y_train.append([i,0])
    
# converting x_train and y_train into numpy array
x_train,y_train = np.array(x_train), np.array(y_train)

In [23]:
x_train

array([[0.66251258, 0.65591458, 0.68377216, ..., 0.49730093, 0.43058964,
        0.20113301],
       [0.65591458, 0.68377216, 0.65391532, ..., 0.43058964, 0.20113301,
        0.28693767],
       [0.68377216, 0.65391532, 0.61042982, ..., 0.20113301, 0.28693767,
        0.20376533],
       ...,
       [0.36567802, 0.37494159, 0.37447508, ..., 0.67580795, 0.72519155,
        0.78050658],
       [0.37494159, 0.37447508, 0.45248254, ..., 0.72519155, 0.78050658,
        0.76674443],
       [0.37447508, 0.45248254, 0.43885362, ..., 0.78050658, 0.76674443,
        0.7372542 ]])

In [25]:
y_train

array([[ 60,   0],
       [ 61,   0],
       [ 62,   0],
       [ 63,   0],
       [ 64,   0],
       [ 65,   0],
       [ 66,   0],
       [ 67,   0],
       [ 68,   0],
       [ 69,   0],
       [ 70,   0],
       [ 71,   0],
       [ 72,   0],
       [ 73,   0],
       [ 74,   0],
       [ 75,   0],
       [ 76,   0],
       [ 77,   0],
       [ 78,   0],
       [ 79,   0],
       [ 80,   0],
       [ 81,   0],
       [ 82,   0],
       [ 83,   0],
       [ 84,   0],
       [ 85,   0],
       [ 86,   0],
       [ 87,   0],
       [ 88,   0],
       [ 89,   0],
       [ 90,   0],
       [ 91,   0],
       [ 92,   0],
       [ 93,   0],
       [ 94,   0],
       [ 95,   0],
       [ 96,   0],
       [ 97,   0],
       [ 98,   0],
       [ 99,   0],
       [100,   0],
       [101,   0],
       [102,   0],
       [103,   0],
       [104,   0],
       [105,   0],
       [106,   0],
       [107,   0],
       [108,   0],
       [109,   0],
       [110,   0],
       [111,   0],
       [112,

In [27]:
x_train.shape

(191, 60)

In [28]:
# reshaping dataset
x_train = x_train.reshape(191, 60, 1)
x_train.shape

(191, 60, 1)